#!/usr/bin/env node
import fs from "fs";
import path from "path";

const projectName = process.argv[2] || "my-user-app";
const projectPath = path.join(process.cwd(), projectName);

// 1. Create project folder
if (!fs.existsSync(projectPath)) {
  fs.mkdirSync(projectPath);
  console.log(`✅ Created folder ${projectName}`);
}

// 2. Create package.json
const packageJson = {
  name: projectName,
  version: "1.0.0",
  main: "index.js",
  scripts: {
    start: "node login.js"
  }
};

fs.writeFileSync(
  path.join(projectPath, "package.json"),
  JSON.stringify(packageJson, null, 2)
);
console.log("✅ Created package.json");

// 3. Create files
const files = ["login.ts", "logout.ts", "register.ts"];

files.forEach((file) => {
  const filePath = path.join(projectPath, file);
  fs.writeFileSync(filePath, `// ${file} generated by create-user\n`);
  console.log(`✅ Created ${file}`);
});

console.log("🎉 Done!");
console.log(`➡️ Next steps:`);
console.log(`cd ${projectName}`);
console.log("pnpm install");
console.log("pnpm start");
