name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install pnpm first
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Then setup Node.js (this will pick up pnpm correctly)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Version packages
        run: pnpm changeset version

      - name: Install again after versioning
        run: pnpm install --frozen-lockfile

      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: version packages [skip ci]"

      - name: Publish packages
        run: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
