name: Auto Publish Packages

# Ensure workflow has correct permissions
permissions:
  contents: write   # allow pushing commits
  packages: write   # allow publishing packages

on:
  push:
    branches:
      - main      # Trigger on main branch
    tags:
      - 'v*'      # Optional: trigger on version tags like v0.2.1

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # allows pushing commits using GITHUB_TOKEN

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      # 3. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. Authenticate npm
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # 6. Bump versions & generate changelog
      - name: Version packages
        run: pnpm changeset version

      # 7. Commit version bumps & changelog
      - name: Commit version bumps
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): version packages [skip ci]" || echo "No changes to commit"
          git push

      # 8. Publish updated packages to npm
      - name: Publish packages
        run: pnpm changeset publish
