name: Auto Publish Packages

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js (with npm registry + token)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 3. Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      # 4. Install dependencies
      - run: pnpm install --frozen-lockfile

      # 5. Build packages
      - run: pnpm -r run build

      # 6. Version packages
      - run: pnpm changeset version

      # 7. Commit version bumps
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): version packages [skip ci]" || echo "No changes to commit"
          git push

      # 8. Publish to npm
      - run: pnpm changeset publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
