name: Auto Publish Packages

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # optional, trigger on tags like v0.2.1

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      # 3. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. Authenticate npm for your scope
      - name: Authenticate with npm
        run: |
          echo "@muzzamilhassan:registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      # 6. Build packages
      - name: Build packages
        run: pnpm -r run build

      # 7. Bump versions & generate changelog
      - name: Version packages
        run: pnpm changeset version

      # 8. Commit version bumps & changelog
      - name: Commit version bumps
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): version packages [skip ci]" || echo "No changes to commit"
          git push

      # 9. Publish updated packages to npm
      - name: Publish packages
        run: pnpm changeset publish --access public
